# fly.toml app configuration file generated for divine-meadow-1824 on 2023-07-26T09:38:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "divine-meadow-1824"
primary_region = "iad"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
